apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster-role.yaml
- cluster-role-binding.yaml
- prometheus-deployment.yaml
- prometheus-service.yaml
configMapGenerator:
- name: prometheus-server-conf
  files:
  - prometheus.yaml
