apiVersion: v1
kind: Service
metadata:
  name: pgk-express-metrics
  labels:
    app: "pgk-express"
spec:
  type: ClusterIP
  ports:
    - port: 9991
      targetPort: monitoring
  selector:
    app: "pgk-express"