apiVersion: v1
kind: Service
metadata:
  name: pgk-express
  labels:
    app: "pgk-express"
spec:
  type: ClusterIP
  ports:
    - port: 4000
      targetPort: app-port
  selector:
    app: "pgk-express"