apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: grafana
configMapGenerator:
- name: grafana-prometheus-datasource
  files:
  - datasources.yaml
resources:
- deployment.yaml
- service.yaml
images:
- name: grafana/grafana
  newTag: 6.1.6